language: ruby
node_js:
  - "2.0"
env:
  - NGINX_BUILD=1.2.9
services:
  - memcached
  before_install:
  - sudo add-apt-repository ppa:bpaquet/zeromq3-precise -y
  - sudo add-apt-repository ppa:bpaquet/zeromq4-precise -y
  - sudo apt-get update
  - sudo apt-get install -y logrotate
  - sudo apt-get install -y libzmq1=${ZEROMQ_VERSION} libzmq-dev=${ZEROMQ_VERSION}
  - npm install -g npm
